apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/mold/
- ./dev-mold-configmap.yaml
- ./dev-mold-vault.yaml
patches:
- path: ./dev-mold-patch-deploy.yaml
- path: ./dev-mold-patch-service.yaml
- path: ./dev-mold-vault-patch.yaml
images:
- name: metrics-image
  newName: dmitryovchinnikov/blueprint/mold-api-metrics
  newTag: 0.0.1
- name: service-image
  newName: dmitryovchinnikov/blueprint/mold-api
  newTag: 0.0.1
